spring:
  application:
    name: cdp-grpc-server
  main:
    banner-mode: "off"

grpc:
  port: 6565

rocketmq:
  producer:
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    default: false