# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12.8
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080